// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3KQxUbs1rObD7OtpJSijVFVkokbGhDcE',
    appId: '1:605525940234:web:d4729a06476dba5bb1e7f3',
    messagingSenderId: '605525940234',
    projectId: 'yacht-rental-flutter-app',
    authDomain: 'yacht-rental-flutter-app.firebaseapp.com',
    storageBucket: 'yacht-rental-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHF7TRRVP3Pvp62t0lNAyZvTuq4JhH6r8',
    appId: '1:605525940234:android:060a994f4bb0db91b1e7f3',
    messagingSenderId: '605525940234',
    projectId: 'yacht-rental-flutter-app',
    storageBucket: 'yacht-rental-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU7UJsMn1KPH77jtJbKIdTNYyZPG5LOrY',
    appId: '1:605525940234:ios:cb75909494e1d2c4b1e7f3',
    messagingSenderId: '605525940234',
    projectId: 'yacht-rental-flutter-app',
    storageBucket: 'yacht-rental-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationProject',
  );

}