// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVXQzksrRFMI8EWBWW4Kh0jlfsURGlYVU',
    appId: '1:706143191898:web:b177c6546d51e5e8596963',
    messagingSenderId: '706143191898',
    projectId: 'yacht-app-c9b45',
    authDomain: 'yacht-app-c9b45.firebaseapp.com',
    storageBucket: 'yacht-app-c9b45.firebasestorage.app',
    measurementId: 'G-39MLN2HQ0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_C0ZGi2vdUUZ10XWpCRAMZP30WK66lsk',
    appId: '1:706143191898:android:f597b0a13e062d37596963',
    messagingSenderId: '706143191898',
    projectId: 'yacht-app-c9b45',
    storageBucket: 'yacht-app-c9b45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCyP2l_7tegVRbOBJg0Jtz6-1UkVDNpII',
    appId: '1:706143191898:ios:d7fa72c8df90617f596963',
    messagingSenderId: '706143191898',
    projectId: 'yacht-app-c9b45',
    storageBucket: 'yacht-app-c9b45.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationProject',
  );

}